### ISSUE TITLE
Can someone make jar

### ISSUE THREAD

**Issue by maciey** [igniterealtime/openfire-broadcast-plugin#3]
Can someone help creating jar from this code so I can upload it and start using with newest OF ?

**Comment by deleolajide** [comment]
https://github.com/igniterealtime/openfire-broadcast-plugin/releases/tag/v1.9.1

**Comment by maciey** [comment]
@deleolajide - you are the Man !!!
Thanks! It is working like a harm

**Comment by TerVel76** [comment]
All good. Thanks!
Openfire 4.3.2 / Opensuse 13.2
